### ISSUE TITLE
Brainstorming how to test all the code

### ISSUE THREAD

**Issue by josearmandojacq** [aemal/SkypeClone#118]

**Comment by spielhoelle** [comment]
A issue related to brain which is assigned to me?
![200](https://user-images.githubusercontent.com/6317641/34905679-63bfb640-f85e-11e7-9c7d-474a66fd14b4.gif)

**Comment by josearmandojacq** [comment]
hahahahahah

**Comment by aemal** [comment]
@spielhoelle is it possible you take care of testing? 🙏  Jest? or anything better you have in mind.

**Comment by spielhoelle** [comment]
I'd love to use [cypress.io](www.cypress.io) in a real environment. If somebody provides me some **specs** which lead me the path, I could imagine to implement it and finally contribute something to your project <3

**Comment by aemal** [comment]
very nice! cypress looks to be a blackbox testing tool. Can we do white box testing as well?
The specs can be derived by the usage i.e. checking responsiveness, typing, search friends, click events, etc. You could do a few of them and let the rest to the students.

We could use cypress for UI testing and Jest for unit testing, in [this example](https://repl.it/@amasad/try-jest) you can get an overall view of how it works.

**Comment by spielhoelle** [comment]
Cypress offers mechanics to seed the database, so it has some kind of integration/unit testing inside. I have no big experience with it - but i think it will do the trick.

@aemal I made a [PR ](https://github.com/aemal/SkypeClone/pull/119)to add a travis config to our project if that is good for you and had nothing else planned yet.
To make the integration works you need to add the travis application to your github repo

**Comment by aemal** [comment]
@spielhoelle That is good for me and not have other plans yet. As a collaborator you can merge PRs and plz let me know if you need any specific permissions.

**Comment by spielhoelle** [comment]
Here's a [initial test](https://github.com/aemal/SkypeClone/pull/120). Check it out if something like that fits to our needs

For travis i need to access the repo settings - or you merge the travis PR and the connection could be made pretty easily somewhere

**Comment by josearmandojacq** [comment]
![img_0946](https://user-images.githubusercontent.com/24357305/34935121-14e744ae-f9dd-11e7-9523-2ad3d00361bf.jpg)
it's taking too long

**Comment by josearmandojacq** [comment]
😭

**Comment by aemal** [comment]
@josearmandojacq does it take that long each time you execute it? Apparently it seems like it is just for the first time when it download and install it.

**Comment by spielhoelle** [comment]
The first time it takes a while, but then it run the ./node command and the electon window comes automatically in my case

**Comment by josearmandojacq** [comment]
yep!!! everytime

**Comment by spielhoelle** [comment]
Lets see tomorrow. I come at 9

**Comment by aemal** [comment]
@spielhoelle just read this on cypress website and wanted to share:

Cypress is not a general automation framework, nor is it a unit testing framework for your back end services.

**Comment by josearmandojacq** [comment]
english, please 🤯🤯
