### ISSUE TITLE
Stickers to give away

### ISSUE THREAD

**Issue by aemal** [aemal/SkypeClone#128]
@sareh88 @josearmandojacq @Yassermorteza @spielhoelle 
Very high quality JavaScript ecosystem stickers waiting to be given as gifts ONLY if you finish the database connectivity until Tuesday next week. 🎉  👍  👨‍💻 

Check the photo: https://ibb.co/d8DGrw

**Comment by sareh88** [comment]
Done already  👍🏻

**Comment by josearmandojacq** [comment]
🤟🏽

**Comment by aemal** [comment]
@spielhoelle and I will need to check it first 😄 

Please let us know when to test it.
