### ISSUE TITLE
Create /save_profile REST API

### ISSUE THREAD

**Issue by aemal** [aemal/SkypeClone#17]

**Comment by gen-failure** [comment]
So far, the profile consists of firstName and lastName, both items are mandatory for the record and usually will be retrieved from oauth2 provider. So the question for @aemal is,  what exactly should this endpoint do?

**Comment by aemal** [comment]
I prefer adding firstName and lastName on the signup page as well and leaving the mandatory fields on the schema, as on the contact list page and everywhere we would need to show Full Name. I prefer making a Full Name virtual field on Mongoose as well. 

I love it, communication started ;)
