### ISSUE TITLE
Create /decline_friend REST API

### ISSUE THREAD

**Issue by aemal** [aemal/SkypeClone#19]

**Comment by josearmandojacq** [comment]
what is the idea behind decline a user?

**Comment by aemal** [comment]
Lets say User A requested User B and then User B declined, this endpoint will be called and it should do the following:

1.  remove the userID of A from User.contacts.pending of User B 
2. remove the userID of B from User.contacts.requested of User A
3. add the userID of B in User.contacts.declined of User A

**Comment by aemal** [comment]
Nice Job! I see activities at 10pm ;) @josearmandojacq
