### ISSUE TITLE
Search friend for adding /search_contacts REST API

### ISSUE THREAD

**Issue by aemal** [aemal/SkypeClone#27]

**Comment by gen-failure** [comment]
shoudn't be this called search user or  /user/search ? or do you really want to search in friend list only?

**Comment by aemal** [comment]
Yes it should be a search in the list of added friends. There must be another REST API for searching contacts.

**Comment by gen-failure** [comment]
But this list should be available all the time in client anyway, why do we need rest api for this?

**Comment by aemal** [comment]
Agreed! We will do the search on UI level. I may have thought of a pagination (load on scroll) for contacts, but we can load all the contacts of a user at once. So you can delete this API, it is not needed.
