### ISSUE TITLE
Profile handler

### ISSUE THREAD

**Issue by josearmandojacq** [aemal/SkypeClone#83]
What is the core function of the edit profile function(API), I think we should discuss it on class

**Comment by aemal** [comment]
We can discuss it over here!!! 😄 

The purpose is to change the profile settings of the currently logged in user. It is also known as Settings page, where you can change your First Name, Last Name, etc.

**Comment by josearmandojacq** [comment]
Ok, I need some feedback on the code:
In the encryption part, we need to find a way to ask first or check if the user change the password and then and only then encrypt the new password ;)

**Comment by aemal** [comment]
If I didn't misunderstand, you need to check if the password was changed then you have to hash it otherwise you don't. Right?

**Comment by aemal** [comment]
I just realized that the screen for Change Password is not there in the wireframe. This would be just a popup dialog with one text box (or two, if you want to put confirm password). It will need to hit a new REST API endpoint which will just blindly hash it and update it in the database. Hence you don't need to take care of the password in the edit profile handler. 😄
